In [1]:
from google.colab import files
uploaded=files.upload()

Saving heights.csv to heights.csv

In [2]:
import pandas as pd
df=pd.read_csv('heights.csv')

In [3]:
df.head()

    name  height
0  mohan     5.9
1  maria     5.2
2  sakib     5.1
3    tao     5.5
4  virat     4.9

In [6]:
#now for outlier i am considering 0.95
max_threshold=df['height'].quantile(0.95)
max_threshold

9.689999999999998

In [7]:
df[df['height']>max_threshold] #outlier

    name  height
9  imran    14.5

In [9]:
min_threshold=df['height'].quantile(0.05)
min_threshold

3.6050000000000004

In [10]:
df[df['height']<min_threshold] #outlier

      name  height
12  yoseph     1.2

In [13]:
df=df[(df['height']>min_threshold)&(df['height']<max_threshold)]

In [15]:
df

       name  height
0     mohan     5.9
1     maria     5.2
2     sakib     5.1
3       tao     5.5
4     virat     4.9
5    khusbu     5.4
6    dmitry     6.2
7    selena     6.5
8      john     7.1
10     jose     6.1
11  deepika     5.6
13    binod     5.5

In [16]:
#for complex data
from google.colab import files
uploaded=files.upload()

Saving bhp.csv to bhp.csv

In [17]:
df=pd.read_csv('bhp.csv')

In [18]:
df.head()

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250

In [19]:
df.shape

(13200, 7)

In [20]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13200.000000  13200.000000  13200.000000  13200.000000    1.320000e+04
mean    1555.302783      2.691136    112.276178      2.800833    7.920337e+03
std     1237.323445      1.338915    149.175995      1.292843    1.067272e+05
min        1.000000      1.000000      8.000000      1.000000    2.670000e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.267000e+03
50%     1275.000000      2.000000     71.850000      3.000000    5.438000e+03
75%     1672.000000      3.000000    120.000000      3.000000    7.317000e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [21]:
max_threshold=df['price_per_sqft'].quantile(0.999)
min_threshold=df['price_per_sqft'].quantile(0.001)

In [22]:
max_threshold

50959.36200000098

In [23]:
min_threshold

1366.184

In [24]:
df[df['price_per_sqft']<min_threshold]

        location       size  total_sqft  bath  price  bhk  price_per_sqft
665    Yelahanka      3 BHK     35000.0   3.0  130.0    3             371
798        other  4 Bedroom     10961.0   4.0   80.0    4             729
1867       other  3 Bedroom     52272.0   2.0  140.0    3             267
2392       other  4 Bedroom      2000.0   3.0   25.0    4            1250
3934       other      1 BHK      1500.0   1.0   19.5    1            1300
5343       other      9 BHK     42000.0   8.0  175.0    9             416
5417      Ulsoor      4 BHK     36000.0   4.0  450.0    4            1250
5597    JP Nagar      2 BHK      1100.0   1.0   15.0    2            1363
7166   Yelahanka  1 Bedroom     26136.0   1.0  150.0    1             573
7862    JP Nagar      3 BHK     20000.0   3.0  175.0    3             875
8300     Kengeri      1 BHK      1200.0   1.0   14.0    1            1166
9144       other  4 Bedroom     10961.0   4.0   80.0    4             729
11635      Begur      3 BHK      2400.0   3.0   12.0    3             500
12355      other      4 BHK     16335.0   4.0  149.0    4             912

In [25]:
df[df['price_per_sqft']>max_threshold]

,location,size,total_sqft,bath,price,bhk,price_per_sqft
345,other,3 Bedroom,11.0,3.0,74.0,3,672727
1005,other,1 BHK,15.0,1.0,30.0,1,200000
1106,other,5 Bedroom,24.0,2.0,150.0,5,625000
4044,Sarjapur Road,4 Bedroom,1.0,4.0,120.0,4,12000000
4924,other,7 BHK,5.0,7.0,115.0,7,2300000
5911,Mysore Road,1 Bedroom,45.0,1.0,23.0,1,51111
6356,Bommenahalli,4 Bedroom,2940.0,3.0,2250.0,4,76530
7012,other,1 BHK,650.0,1.0,500.0,1,76923
7575,other,1 BHK,425.0,1.0,750.0,1,176470
7799,other,4 BHK,2000.0,3.0,1063.0,4,53150
8307,Bannerghatta Road,5 BHK,2500.0,4.0,1400.0,5,56000
9436,Indira Nagar,4 Bedroom,2400.0,5.0,1250.0,4,52083
11447,Whitefield,4 Bedroom,60.0,4.0,218.0,4,363333
12328,other,4 Bedroom,4350.0,8.0,2600.0,4,59770

In [26]:
newdf=df[(df['price_per_sqft']>min_threshold)&(df['price_per_sqft']<max_threshold)]

In [27]:
newdf.shape

(13172, 7)

### **Exercise**

In [28]:
from google.colab import files
uploaded=files.upload()

Saving AB_NYC_2019.csv to AB_NYC_2019.csv

In [29]:
df=pd.read_csv('AB_NYC_2019.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [30]:
df.shape

(48895, 16)

In [32]:
df.price.describe()

count    48895.000000
mean       152.720687
std        240.154170
min          0.000000
25%         69.000000
50%        106.000000
75%        175.000000
max      10000.000000
Name: price, dtype: float64

In [33]:
min_threshold=df['price'].quantile(0.05)

In [34]:
max_threshold=df['price'].quantile(0.999)

In [35]:
min_threshold

40.0

In [36]:
max_threshold

3000.0

In [38]:
df[df.price<min_threshold]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
36,11452,Clean and Quiet in Brooklyn,7355,Vt,Brooklyn,Bedford-Stuyvesant,40.68876,-73.94312,Private room,35,60,0,NaN,NaN,1,365
249,62452,A SpeciaL!! Private Room in NY,303939,Lissette,Staten Island,Tompkinsville,40.63536,-74.08537,Private room,36,2,193,2019-06-25,1.85,6,360
250,62461,B NYC Staten Alternative...,303939,Lissette,Staten Island,Tompkinsville,40.63627,-74.08543,Private room,37,2,147,2019-06-10,1.44,6,0
251,62787,C Private Room By The Ferry,303939,Lissette,Staten Island,Tompkinsville,40.63518,-74.08546,Private room,37,2,177,2019-07-02,1.71,6,320
256,63320,D Private Che@p Room 2 Explore NYC,303939,Lissette,Staten Island,Tompkinsville,40.63481,-74.08519,Private room,36,2,333,2019-07-02,3.19,6,340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48851,36455649,#7 New Hotel-Like Private Room KING bed near JFK,263504959,David,Queens,Woodhaven,40.69137,-73.86591,Private room,35,1,0,NaN,NaN,8,341
48852,36455809,"Cozy Private Room in Bushwick, Brooklyn",74162901,Christine,Brooklyn,Bushwick,40.69805,-73.92801,Private room,30,1,1,2019-07-08,1.00,1,1
48867,36473044,The place you were dreaming for.(only for guys),261338177,Diana,Brooklyn,Gravesend,40.59080,-73.97116,Shared room,25,1,0,NaN,NaN,6,338
48868,36473253,Heaven for you(only for guy),261338177,Diana,Brooklyn,Gravesend,40.59118,-73.97119,Shared room,25,7,0,NaN,NaN,6,365
48871,36475746,A LARGE ROOM - 1 MONTH MINIMUM - WASHER&DRYER,144008701,Ozzy Ciao,Manhattan,Harlem,40.82233,-73.94687,Private room,35,29,0,NaN,NaN,2,31

In [39]:
df[df.price>max_threshold]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1862,826690,"Sunny, Family-Friendly 2 Bedroom",4289240,Lucy,Brooklyn,Prospect Heights,40.67919,-73.97191,Entire home/apt,4000,4,0,NaN,NaN,1,83
2698,1448703,Beautiful 1 Bedroom in Nolita/Soho,213266,Jessica,Manhattan,Nolita,40.72193,-73.99379,Entire home/apt,5000,1,2,2013-09-28,0.03,1,365
3537,2110145,UWS 1BR w/backyard + block from CP,2151325,Jay And Liz,Manhattan,Upper West Side,40.77782,-73.97848,Entire home/apt,6000,14,17,2015-02-17,0.27,1,359
3695,2224896,NYC SuperBowl Wk 5 Bdrs River View,11353904,Todd,Manhattan,Upper West Side,40.79476,-73.97299,Entire home/apt,4000,1,0,NaN,NaN,1,0
3720,2243699,"SuperBowl Penthouse Loft 3,000 sqft",1483320,Omri,Manhattan,Little Italy,40.71895,-73.99793,Entire home/apt,5250,1,0,NaN,NaN,1,0
3774,2271504,SUPER BOWL Brooklyn Duplex Apt!!,11598359,Jonathan,Brooklyn,Clinton Hill,40.68766,-73.96439,Entire home/apt,6500,1,0,NaN,NaN,1,0
3788,2281142,Prime NYC Location for Super Bowl,1427243,Jordana,Manhattan,East Village,40.73323,-73.98859,Entire home/apt,3750,1,0,NaN,NaN,1,0
4345,2919330,NearWilliamsburg bridge 11211 BK,14908606,Bianca,Brooklyn,Bedford-Stuyvesant,40.69572,-73.95731,Private room,5000,6,10,2016-01-02,0.16,1,363
4376,2952861,Photography Location,1177497,Jessica,Brooklyn,Clinton Hill,40.69127,-73.96563,Entire home/apt,4500,1,5,2018-12-29,0.09,11,365
4377,2953058,Film Location,1177497,Jessica,Brooklyn,Clinton Hill,40.69137,-73.96723,Entire home/apt,8000,1,1,2016-09-15,0.03,11,365
6530,4737930,Spanish Harlem Apt,1235070,Olson,Manhattan,East Harlem,40.79264,-73.93898,Entire home/apt,9999,5,1,2015-01-02,0.02,1,0
9151,7003697,Furnished room in Astoria apartment,20582832,Kathrine,Queens,Astoria,40.76810,-73.91651,Private room,10000,100,2,2016-02-13,0.04,1,0
12342,9528920,"Quiet, Clean, Lit @ LES & Chinatown",3906464,Amy,Manhattan,Lower East Side,40.71355,-73.98507,Private room,9999,99,6,2016-01-01,0.14,1,83
15560,12520066,Luxury townhouse Greenwich Village,66240032,Linda,Manhattan,Greenwich Village,40.73046,-73.99562,Entire home/apt,6000,1,0,NaN,NaN,1,0
17665,13882394,VIP Duplex Townhouse with Private Garden!!!,49186997,Joseph,Manhattan,Greenwich Village,40.73305,-73.99373,Entire home/apt,3800,30,2,2017-01-27,0.06,1,180
17692,13894339,Luxury 1 bedroom apt. -stunning Manhattan views,5143901,Erin,Brooklyn,Greenpoint,40.73260,-73.95739,Entire home/apt,10000,5,5,2017-07-27,0.16,1,0
21821,17537893,The Otheroom Bar/Event/Filming Space -read det...,18037301,James,Manhattan,West Village,40.73571,-74.00780,Entire home/apt,4000,1,0,NaN,NaN,1,173
22353,18051877,Victorian Film location,2675644,Alissa,Staten Island,Randall Manor,40.63952,-74.09730,Entire home/apt,5000,1,0,NaN,NaN,1,344
25825,20654227,Fulton 2,100069033,Sarah-2,Brooklyn,Cypress Hills,40.68185,-73.88128,Entire home/apt,5000,2,4,2018-01-03,0.18,1,0
25901,20692563,Greenwich Village Townhome with Private Garden!,147814925,Lloyd,Manhattan,Greenwich Village,40.73300,-73.99413,Entire home/apt,3900,30,7,2018-03-13,0.32,1,180
26739,21238053,Broadway 1,153497815,Sarah-B,Brooklyn,Bedford-Stuyvesant,40.68742,-73.91957,Entire home/apt,5000,2,8,2017-12-09,0.38,1,0
28946,22296097,Chelsea Gallery Space for events and exhibitions,3750764,Kevin,Manhattan,Chelsea,40.74913,-74.00373,Private room,3210,1,0,NaN,NaN,6,364
28947,22296197,"Chelsea Gallery for events, exhibitions, fashion",3750764,Kevin,Manhattan,Chelsea,40.74888,-74.00481,Entire home/apt,4160,1,0,NaN,NaN,6,364
29238,22436899,1-BR Lincoln Center,72390391,Jelena,Manhattan,Upper West Side,40.77213,-73.98665,Entire home/apt,10000,30,0,NaN,NaN,1,83
29662,22779726,East 72nd Townhouse by (Hidden by Airbnb),156158778,Sally,Manhattan,Upper East Side,40.76824,-73.95989,Entire home/apt,7703,1,0,NaN,NaN,12,146
29663,22779746,East 7th Street III by (Hidden by Airbnb),156158778,Sally,Manhattan,East Village,40.72779,-73.98644,Entire home/apt,3518,1,0,NaN,NaN,12,215
29664,22780103,Park Avenue Mansion by (Hidden by Airbnb),156158778,Sally,Manhattan,Upper East Side,40.78517,-73.95270,Entire home/apt,6419,1,0,NaN,NaN,12,45
30268,23377410,Beautiful/Spacious 1 bed luxury flat-TriBeCa/Soho,18128455,Rum,Manhattan,Tribeca,40.72197,-74.00633,Entire home/apt,8500,30,2,2018-09-18,0.18,1,251
34851,27629043,A Night at Anchor Aboard Yacht Ventura,45863742,James,Manhattan,Battery Park City,40.71364,-74.01758,Entire home/apt,3750,1,0,NaN,NaN,1,365
37194,29547314,Apartment New York \nHell’s Kitchens,35303743,Patricia,Manhattan,Upper West Side,40.76835,-73.98367,Private room,6500,30,0,NaN,NaN,1,97
37864,29964348,NYC HOLIDAY!!!! April 15- May 15,2039658,Pam,Manhattan,Upper East Side,40.76519,-73.96874,Entire home/apt,3600,31,0,NaN,NaN,1,358
38000,30035166,4-Floor Unique Event Space 50P Cap. - #10299B,172611460,Rasmus,Manhattan,Harlem,40.82511,-73.94961,Entire home/apt,5000,1,2,2019-02-23,0.38,2,150
39243,30589636,Furnished 1000sq large 2bed + office in Harlem,229458601,Kay,Manhattan,Harlem,40.81315,-73.95110,Entire home/apt,3200,90,0,NaN,NaN,1,365
40433,31340283,2br - The Heart of NYC: Manhattans Lower East ...,4382127,Matt,Manhattan,Lower East Side,40.71980,-73.98566,Entire home/apt,9999,30,0,NaN,NaN,1,365
41216,32054910,West 88th Street by (Hidden by Airbnb),156158778,Sally,Manhattan,Upper West Side,40.78742,-73.97011,Entire home/apt,3512,1,0,NaN,NaN,12,124
42523,33007610,70' Luxury MotorYacht on the Hudson,7407743,Jack,Manhattan,Battery Park City,40.71162,-74.01693,Entire home/apt,7500,1,0,NaN,NaN,1,364
42542,33029434,West 84th Street by (Hidden by Airbnb),156158778,Sally,Manhattan,Upper West Side,40.78545,-73.97123,Entire home/apt,3613,1,1,2019-06-15,1.00,12,158
42736,33171891,30 days minimum Time square West Midtown apart...,177396569,Yanina,Manhattan,Hell's Kitchen,40.76043,-73.99132,Entire home/apt,4100,30,0,NaN,NaN,3,180
43009,33397385,Midtown Manhattan great location (Gramacy park),16105313,Debra,Manhattan,Midtown,40.74482,-73.98367,Entire home/apt,5100,30,1,2019-06-22,1.00,2,343
43670,33796251,Beautiful private Brooklyn room with kitchenette,8748976,Jeffrey,Brooklyn,Bedford-Stuyvesant,40.68807,-73.95426,Private room,4200,114,0,NaN,NaN,1,347
44034,33998396,3000 sq ft daylight photo studio,3750764,Kevin,Manhattan,Chelsea,40.75060,-74.00388,Entire home/apt,6800,1,0,NaN,NaN,6,364
45666,34895693,Gem of east Flatbush,262534951,Sandra,Brooklyn,East Flatbush,40.65724,-73.92450,Private room,7500,1,8,2019-07-07,6.15,2,179
45867,34981637,bay ridge & sunset park furnished apartment,263564234,Nony,Brooklyn,Bay Ridge,40.63087,-74.02006,Entire home/apt,4200,60,0,NaN,NaN,1,90
46614,35345358,Northside Williamsburg Stunner,956324,Alex,Brooklyn,Williamsburg,40.71705,-73.96470,Entire home/apt,4500,30,0,NaN,NaN,1,365
48043,36056808,Luxury TriBeCa Apartment at an amazing price,271248669,Jenny,Manhattan,Tribeca,40.71206,-74.00999,Entire home/apt,6500,180,0,NaN,NaN,1,365

In [47]:
newdf=df[(df.price>min_threshold)&(df.price<max_threshold)]

In [48]:
newdf.sample(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
10778,8292864,Charming East Village Apartment,19194060,Ryan,Manhattan,East Village,40.72410,-73.97992,Entire home/apt,600,3,0,NaN,NaN,1,0
1898,841075,Spacious and Clean Brooklyn Flat,4392420,John,Brooklyn,Bushwick,40.70366,-73.92690,Entire home/apt,85,15,22,2016-10-22,0.28,1,0
40940,31839994,Private house with backyard overlooking park.,40160805,Cherokee,Queens,Flushing,40.75406,-73.80156,Entire home/apt,159,3,1,2019-06-30,1.00,1,78
15201,12147723,Luxury Wall St. Apartment Building,5120853,Mackenzie,Manhattan,Financial District,40.70433,-74.00782,Entire home/apt,175,2,2,2016-07-08,0.05,1,0
28916,22283652,Simple stay in heart of Chelsea / Meatpacking,24478039,Harutoshi,Manhattan,Chelsea,40.74247,-74.00234,Entire home/apt,285,3,1,2018-01-01,0.05,1,0

In [49]:
newdf.shape

(46029, 16)

In [50]:
newdf.price.describe()

count    46029.000000
mean       153.991744
std        155.195268
min         41.000000
25%         75.000000
50%        115.000000
75%        180.000000
max       2999.000000
Name: price, dtype: float64